name: Daily Multi-API Report

on:
  schedule:
    # 19:30 UTC = 01:00 AM IST
    - cron: "30 19 * * *"
  workflow_dispatch:  # allows manual run

jobs:
  run-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Report Script
        env:
          API1_URL: ${{ secrets.API1_URL }}   # or leave empty to use default JSONPlaceholder
          API2_URL: ${{ secrets.API2_URL }}
          API3_URL: ${{ secrets.API3_URL }}
          API_KEY:  ${{ secrets.API_KEY }}    # only if needed

          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          TO_EMAIL:  ${{ secrets.TO_EMAIL }}
        run: python report_generator.py
